import Head from "next/head";
import Component from "layouts/Component";
interface HeadingProps {
  title?: string;
}

export default function Heading({ title = "" }: HeadingProps): JSX.Element {
  return (
    <Component wrappedElement="fragment">
      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Component>
  );
}
